language: node_js
deploy:
  provider: heroku
  api_key:
    secure: 5bad819c-41ae-4d7a-b076-c546bfd8822a
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - npm run build
after_script: # Upload coverage reports 
  - COVERALLS_REPO_TOKEN=rTqe21yrKEen5E6GX1Vd1CuwVKs1oQJU1 npm run coveralls