const EventImage = require('./assets/event.jpg');
const EventImage2 = require('./assets/event-2.jpg');
const EventImage3 = require('./assets/event-3.jpg');

module.exports = {
  upcomingEvents: [
    {
      id: '0',
      image: EventImage,
      date: 'Wed, 18th Sep 2020',
      title: 'Throwing a Confetti Party',
      time: '06:45 PM WAT',
      organizer: 'Adewusi Victor',
      link: 'https://www.victordid.com',
      shortDesc: "Welcome to the biggest and most exciting virtual event of the year! Join us at Manifest 2020 and bring your entire team. It's 100% Free!",
      longDesc: "MDC's 3rd Annual Convention in Las Vegas, NV was a wild success! We gave away tens of thousands of dollars, had empowering guest speakers like Bob Proctor & Les Brown, and gave recognition to those who continue to make My Daily Choice a success. The event will be remembered as one of the greatest conventions we've ever hosted. However, this year, we are manifesting an event that will be unlike anything we've ever done before. You won't want to miss it!",
      location: 'Online Event',
    },
    {
      id: '1',
      image: EventImage2,
      date: 'Wed, 18th Sep 2020',
      title: 'Throwing a Confetti Party',
      time: '06:45 PM WAT',
      organizer: 'Adewusi Victor',
      link: 'https://www.victordid.com',
      shortDesc: "Welcome to the biggest and most exciting virtual event of the year! Join us at Manifest 2020 and bring your entire team. It's 100% Free!",
      longDesc: "MDC's 3rd Annual Convention in Las Vegas, NV was a wild success! We gave away tens of thousands of dollars, had empowering guest speakers like Bob Proctor & Les Brown, and gave recognition to those who continue to make My Daily Choice a success. The event will be remembered as one of the greatest conventions we've ever hosted. However, this year, we are manifesting an event that will be unlike anything we've ever done before. You won't want to miss it!",
      location: 'Online Event',
    },
    {
      id: '2',
      image: EventImage3,
      date: 'Wed, 18th Sep 2020',
      title: 'Throwing a Confetti Party',
      time: '06:45 PM WAT',
      organizer: 'Adewusi Victor',
      link: 'https://www.victordid.com',
      shortDesc: "Welcome to the biggest and most exciting virtual event of the year! Join us at Manifest 2020 and bring your entire team. It's 100% Free!",
      longDesc: "MDC's 3rd Annual Convention in Las Vegas, NV was a wild success! We gave away tens of thousands of dollars, had empowering guest speakers like Bob Proctor & Les Brown, and gave recognition to those who continue to make My Daily Choice a success. The event will be remembered as one of the greatest conventions we've ever hosted. However, this year, we are manifesting an event that will be unlike anything we've ever done before. You won't want to miss it!",
      location: 'Online Event',
    },
    {
      id: '3',
      image: EventImage,
      date: 'Wed, 18th Sep 2020',
      title: 'Throwing a Confetti Party',
      time: '06:45 PM WAT',
      organizer: 'Adewusi Victor',
      link: 'https://www.victordid.com',
      shortDesc: "Welcome to the biggest and most exciting virtual event of the year! Join us at Manifest 2020 and bring your entire team. It's 100% Free!",
      longDesc: "MDC's 3rd Annual Convention in Las Vegas, NV was a wild success! We gave away tens of thousands of dollars, had empowering guest speakers like Bob Proctor & Les Brown, and gave recognition to those who continue to make My Daily Choice a success. The event will be remembered as one of the greatest conventions we've ever hosted. However, this year, we are manifesting an event that will be unlike anything we've ever done before. You won't want to miss it!",
      location: 'Online Event',
    },
    {
      id: '4',
      image: EventImage2,
      date: 'Wed, 18th Sep 2020',
      title: 'Throwing a Confetti Party',
      time: '06:45 PM WAT',
      organizer: 'Adewusi Victor',
      link: 'https://www.victordid.com',
      shortDesc: "Welcome to the biggest and most exciting virtual event of the year! Join us at Manifest 2020 and bring your entire team. It's 100% Free!",
      longDesc: "MDC's 3rd Annual Convention in Las Vegas, NV was a wild success! We gave away tens of thousands of dollars, had empowering guest speakers like Bob Proctor & Les Brown, and gave recognition to those who continue to make My Daily Choice a success. The event will be remembered as one of the greatest conventions we've ever hosted. However, this year, we are manifesting an event that will be unlike anything we've ever done before. You won't want to miss it!",
      location: 'Online Event',
    },
    {
      id: '5',
      image: EventImage3,
      date: 'Wed, 18th Sep 2020',
      title: 'Throwing a Confetti Party',
      time: '06:45 PM WAT',
      organizer: 'Adewusi Victor',
      link: 'https://www.victordid.com',
      shortDesc: "Welcome to the biggest and most exciting virtual event of the year! Join us at Manifest 2020 and bring your entire team. It's 100% Free!",
      longDesc: "MDC's 3rd Annual Convention in Las Vegas, NV was a wild success! We gave away tens of thousands of dollars, had empowering guest speakers like Bob Proctor & Les Brown, and gave recognition to those who continue to make My Daily Choice a success. The event will be remembered as one of the greatest conventions we've ever hosted. However, this year, we are manifesting an event that will be unlike anything we've ever done before. You won't want to miss it!",
      location: 'Online Event',
    },
  ],
};
